export * from './getAllTutorials';
export * from './getAllCategorias';
export * from './getOneCategoria';
export * from './getAllTests';
export * from './getOneTest';
export * from './getOnePregunta';
export * from './getAllProvincias';
export * from './getAllPreguntas';
export * from './getOneJuego';
